[project]
name = "stormsvcs"
authors = "John Gorman"
version = "0.0.1"
description = "A monorepo of independent custom Synapse Advanced Power-Ups"
readme = "README.md"
license = "LICENSE"
requires-python = ">=3.14"
dependencies = [
    "stormlibpp>=0.10.1",
    "synapse>=2.248.0,<3",
]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
]
